export class DamageSource {
	unblockable: boolean;
	isDamageAllowedInCreativeMode: boolean;
	damageIsAbsolute: boolean;
	hungerDamage: number;
	fireDamage: number;
	projectile: boolean;
	difficultyScaled: boolean;
	magicDamage: boolean;
	explosion: boolean;
	damageType: string;
	damageSourceEntity?: Entity;
	isThornsDamage: boolean;
	indirectEntity?: Entity;
	constructor(damageType: string, entity: Entity, p?: Entity);
	static causeMobDamage(mob: EntityLivingBase): DamageSource;
	static causePlayerDamage(player: EntityPlayer): DamageSource;
	static causeArrowDamage(u: Entity, h: Entity): DamageSource;
	static causeFireballDamage(e: Entity, ie: Entity): DamageSource;
	static causeThrownDamage(e: Entity, ie: Entity): DamageSource;
	static causeIndirectMagicDamage(e: Entity, ie: Entity): DamageSource;
	static causeThornsDamage(e: Entity): DamageSource;
	static setExplosionSource(u: unknown): DamageSource;
	isProjectile(): this["projectile"];
	setProjectile(): this;
	isExplosion(): this["explosion"];
	setExplosion(): this;
	isUnblockable(): this["unblockable"];
	getHungerDamage(): this["hungerDamage"];
	canHarmInCreative(): this["isDamageAllowedInCreativeMode"];
	isDamageAbsolute(): this["isDamageAbsolute"];
	getSourceOfDamage(): Entity | null;
	getEntity(): Entity | null;
	setDamageBypassesArmor(): this;
	setDamageAllowedInCreativeMode(): this;
	setDamageIsAbsolute(): this;
	setFireDamage(): this;
	getDeathMessage(e: Entity): string;
	isFireDamage(): this["fireDamage"];
	getDamageType(): this["damageType"];
	setDifficultyScaled(): this;
	isDifficultyScaled(): this["difficultyScaled"];
	isMagicDamage(): this["magicDamage"];
	setMagicDamage(): this;
	isCreativePlayer(): boolean;
	getIsThornsDamage(): this["isThornsDamage"];
	equals(other: DamageSource): boolean;
	setIsThornsDamage(): this;
}
